name: Deploy on GitHub Pages

on:
  repository_dispatch:
    types: [ deploy-on-github-pages ]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: yarn
      - name: Build website
        run: npm run buildPrefix
        env:
          OBERION_API_KEY: ${{ secrets.OBERION_API_KEY }}
      - name: Deploy website
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./public